import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "./Navbar/Navbar";
import Sidebar from "./components/Sidebar/Sidebar";
import { ReduxProvider } from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CPK note app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <ReduxProvider>
          <Navbar />
          <Sidebar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
